"""Bootstrap the metadata Postgres schema.

Run on first deploy (and on each release; statements are idempotent):

    viamedia-migrate

Or programmatically:
    from viamedia_pipeline.common.migrations import apply
    apply()
"""

import sys

import psycopg

from viamedia_pipeline.common.logging import configure_logging, get_logger
from viamedia_pipeline.common.metadata_db import metadata_dsn, metadata_schema

log = get_logger(__name__)


DDL = """
CREATE SCHEMA IF NOT EXISTS {schema};
SET search_path TO {schema}, public;

-- Pipeline watermarks ---------------------------------------------------
CREATE TABLE IF NOT EXISTS pipeline_watermarks (
    table_fqn   TEXT PRIMARY KEY,
    last_ts     TIMESTAMPTZ NOT NULL,
    last_id     BIGINT       NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Per-chunk run state for resumable bootstraps ---------------------------
CREATE TABLE IF NOT EXISTS pipeline_chunk_state (
    run_id      TEXT NOT NULL,
    chunk_key   TEXT NOT NULL,
    status      TEXT NOT NULL CHECK (status IN ('PENDING','RUNNING','DONE','FAILED')),
    s3_uri      TEXT,
    rows        BIGINT,
    error       TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, chunk_key)
);

CREATE INDEX IF NOT EXISTS pipeline_chunk_state_status_idx
  ON pipeline_chunk_state (run_id, status);

-- PyIceberg SqlCatalog tables are created by PyIceberg itself on first use;
-- we just need the schema to exist.

-- Operational metadata for the gateway view-refresher --------------------
CREATE TABLE IF NOT EXISTS gateway_view_refresh (
    view_name        TEXT PRIMARY KEY,
    iceberg_table    TEXT NOT NULL,
    metadata_location TEXT,
    refreshed_at     TIMESTAMPTZ
);

-- === UI-managed configuration (added 2026-06) ==========================

-- One row per source database ("connection"). Secrets are Fernet-encrypted
-- (see common/crypto.py); each connection targets its own S3 bucket + Iceberg
-- namespace. sync_* globs are a fallback when no explicit selection rows exist.
CREATE TABLE IF NOT EXISTS pipeline_connections (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  TEXT NOT NULL UNIQUE,
    enabled               BOOLEAN NOT NULL DEFAULT true,
    source_dsn_enc        TEXT NOT NULL,
    aws_access_key_enc    TEXT,
    aws_secret_key_enc    TEXT,
    aws_region            TEXT NOT NULL DEFAULT 'us-east-1',
    lake_bucket           TEXT NOT NULL,
    iceberg_namespace     TEXT NOT NULL UNIQUE,
    sync_include          TEXT NOT NULL DEFAULT '',
    sync_exclude          TEXT NOT NULL DEFAULT '',
    sync_object_types     TEXT NOT NULL DEFAULT 'TABLE,VIEW,MATERIALIZED_VIEW',
    sync_schema_blacklist TEXT NOT NULL DEFAULT 'pg_catalog,information_schema,pg_toast',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Explicit per-object sync selection (the UI multi-select). Uncheck => stop sync.
CREATE TABLE IF NOT EXISTS pipeline_sync_selection (
    connection_id BIGINT NOT NULL REFERENCES pipeline_connections(id) ON DELETE CASCADE,
    schema_name   TEXT NOT NULL,
    object_name   TEXT NOT NULL,
    kind          TEXT NOT NULL,
    enabled       BOOLEAN NOT NULL DEFAULT true,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (connection_id, schema_name, object_name)
);

-- Global operational settings (tuning, gateway params) editable from the UI.
CREATE TABLE IF NOT EXISTS pipeline_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Per-object last-sync status (powers the "last synced" display in the UI).
CREATE TABLE IF NOT EXISTS pipeline_object_state (
    connection_id  BIGINT NOT NULL,
    table_fqn      TEXT NOT NULL,
    last_synced_at TIMESTAMPTZ,
    last_kind      TEXT,          -- bootstrap | incremental | reconcile
    last_run_id    TEXT,
    last_rows      BIGINT,
    PRIMARY KEY (connection_id, table_fqn)
);

-- API tokens: scoped to ONE connection, with a role. Only the SHA-256 hash is
-- stored; the plaintext token is shown once at creation.
CREATE TABLE IF NOT EXISTS pipeline_api_tokens (
    id            BIGSERIAL PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT NOT NULL,
    connection_id BIGINT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'viewer',   -- viewer | admin
    token_hash    TEXT NOT NULL UNIQUE,
    token_prefix  TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at  TIMESTAMPTZ,
    revoked       BOOLEAN NOT NULL DEFAULT false
);

-- Web-UI users + their role, gating Microsoft (Azure AD) login. enabled=false
-- or absent => not allowed to log in.
CREATE TABLE IF NOT EXISTS pipeline_users (
    email      TEXT PRIMARY KEY,
    role       TEXT NOT NULL DEFAULT 'viewer',       -- viewer | admin
    enabled    BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add connection scoping to state tables. connection_id defaults to 1 so any
-- pre-existing rows map to the first (migrated) connection.
ALTER TABLE pipeline_watermarks   ADD COLUMN IF NOT EXISTS connection_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE pipeline_chunk_state  ADD COLUMN IF NOT EXISTS connection_id BIGINT NOT NULL DEFAULT 1;

-- Generic watermark value: the watermark column may be a timestamp, a date, or
-- an integer (e.g. an epoch/sequence `updated_at`). last_value stores it as text
-- (parsed back per the live column type); last_ts becomes nullable since
-- non-timestamp watermarks don't populate it.
ALTER TABLE pipeline_watermarks   ADD COLUMN IF NOT EXISTS last_value TEXT;
ALTER TABLE pipeline_watermarks   ALTER COLUMN last_ts DROP NOT NULL;

-- Make the watermark PK composite (connection_id, table_fqn). Idempotent:
-- only swaps if the current PK isn't already 2-column.
DO $mig$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = format('%I.pipeline_watermarks', current_schema())::regclass
          AND contype = 'p'
          AND array_length(conkey, 1) = 2
    ) THEN
        ALTER TABLE pipeline_watermarks DROP CONSTRAINT IF EXISTS pipeline_watermarks_pkey;
        ALTER TABLE pipeline_watermarks
            ADD CONSTRAINT pipeline_watermarks_pkey PRIMARY KEY (connection_id, table_fqn);
    END IF;
END
$mig$;
"""


def apply() -> None:
    dsn, schema = metadata_dsn(), metadata_schema()
    log.info("migrations.applying", schema=schema, dsn_host=_dsn_host(dsn))
    with psycopg.connect(dsn, autocommit=True) as conn, conn.cursor() as cur:
        cur.execute(DDL.format(schema=schema))
    log.info("migrations.done")


def _dsn_host(dsn: str) -> str:
    # Best-effort host extraction for logging without leaking creds.
    import urllib.parse as up

    try:
        return up.urlparse(dsn).hostname or "?"
    except Exception:
        return "?"


def main() -> None:
    configure_logging()
    try:
        apply()
    except Exception as e:
        log.error("migrations.failed", error=str(e))
        sys.exit(1)


if __name__ == "__main__":
    main()
